
title: "Your Name"
description: "Assistant Professor in Economics at Your University"
url: "https://your-username.github.io"
baseurl: ""

author:
  name: "Your Name"
  bio: "Assistant Professor in Economics at Your University"
  location: "United States"
  email: "your.email@university.edu"
  twitter: "yourusername"
  linkedin: "yourusername"
  github: "yourusername"
  orcid: "0000-0000-0000-0000"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

permalink: /:categories/:title/
timezone: America/New_York
