title: "Ankita R. Shinde"
description: "PhD Candidate in Mechanical Engineering specializing in Biomedical Scaffolds and Additive Manufacturing at NYU Tandon"
url: "https://ankitarshinde12.github.io"
baseurl: ""

# SEO and Social Media Meta Tags
locale: "en-US"
name: "Ankita R. Shinde"

# Open Graph / Social Media Preview
og_image: "/assets/images/profile.png"
social:
  name: "Ankita R. Shinde"
  links:
    - "https://www.linkedin.com/in/ankitarshinde12"
    - "https://github.com/ankitarshinde12"

author:
  name: "Ankita R. Shinde"
  bio: "PhD Candidate in Mechanical Engineering | Biomedical Scaffolds & Additive Manufacturing"
  location: "New York, United States"
  email: "axs10184@nyu.edu"
  linkedin: "ankitarshinde12"
  github: "ankitarshinde12"
  orcid: "0000-0001-8521-2659"
  avatar: "/assets/images/profile.png"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=dHAtDPMAAAAJ&hl=en"


remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: false
      read_time: false
      comments: false
      share: false
      related: false

permalink: /:categories/:title/
timezone: America/New_York
