title: "Ankita R. Shinde"
description: "PhD Candidate in Mechanical Engineering at NYU Tandon School of Engineering"
url: "https://ankitarshinde12.github.io"
baseurl: ""

author:
  name: "Ankita R. Shinde"
  bio: "PhD Candidate in Mechanical Engineering | Biomedical Scaffolds & Additive Manufacturing"
  location: "New York, United States"
  email: "axs10184@nyu.edu"
  linkedin: "ankitarshinde12"
  github: "ankitarshinde12"
  orcid: "0000-0001-8521-2659"
  avatar: "/assets/images/profile.png"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

permalink: /:categories/:title/
timezone: America/New_York