
title: "Ankita Shinde"
description: "Assistant Professor in Economics at Your University"
url: "https://ankitarshinde12.github.io"
baseurl: ""

author:
  name: "Ankita Shinde"
  bio: "Assistant Professor in Economics at Your University"
  location: "United States"
  email: "ankitarshinde12@nyu.edu"
  twitter: "Ankita Shinde"
  linkedin: "Ankita Shinde"
  github: "Ankita Shinde"
  orcid: "0000-0000-0000-0000"

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

permalink: /:categories/:title/
timezone: America/New_York
